server:
  port: 7000

spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com:
      jratil:
        shardingdemo1:
          mapper: debug
#spring:
#  shardingsphere:
#    datasource:
#      names: master,slave
#      master:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://192.168.56.102:3306/m_s_demo?characterEncoding=utf-8
#        username: root
#        password: ratil123
#      slave:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://192.168.56.102:3306/m_s_demo?characterEncoding=utf-8
#        username: root
#        password: ratil123
#    sharding:
#      tables:
#        user:
#          actual-data-nodes: master.user${0..1}
#          table-strategy:
#            inline:
#              shardingColumn: id
#              algorithm-expression: user${id % 2}
#          key-generator:
#            column: id
#            type: SNOWFLAKE
#    masterslave:
#      name: datasource
#      master-data-source-name: master
#      slave-data-source-names: slave
#    props:
#      sql:
#        show: true